### ISSUE TITLE
Error while import MonoT5 from Pygaggle

### ISSUE THREAD

**Issue by saurabhg-predii** [neuralmind-ai/visconde#2]
I am running the notebook on Colab on Python v3.9.16
Kindly help me resolve the issue @rodrigonogueira4, @jayralencar.

1 from pygaggle.rerank.base import Query, Text
----> 2 from pygaggle.rerank.transformer import MonoT5
      3 
      4 reranker = MonoT5(model=model)

7 frames
[/usr/local/lib/python3.9/dist-packages/pygaggle/rerank/transformer.py](https://localhost:8080/#) in <module>
     11 import torch
     12 from .base import Reranker, Query, Text
---> 13 from .similarity import SimilarityMatrixProvider
     14 from pygaggle.model import (BatchTokenizer,
     15                             LongBatchEncoder,

[/usr/local/lib/python3.9/dist-packages/pygaggle/rerank/similarity.py](https://localhost:8080/#) in <module>
      3 import torch
      4 
----> 5 from pygaggle.model.encode import SingleEncoderOutput
      6 
      7 

[/usr/local/lib/python3.9/dist-packages/pygaggle/model/__init__.py](https://localhost:8080/#) in <module>
      4 
      5 from .decode import *
----> 6 from .encode import *
      7 from .evaluate import *
      8 from .serialize import *

[/usr/local/lib/python3.9/dist-packages/pygaggle/model/encode.py](https://localhost:8080/#) in <module>
      6 import torch.nn as nn
      7 
----> 8 from .tokenize import BatchTokenizer
      9 from pygaggle.rerank.base import TextType
     10 

[/usr/local/lib/python3.9/dist-packages/pygaggle/model/tokenize.py](https://localhost:8080/#) in <module>
    170 
    171 
--> 172 class SpacySenticizer:
    173     nlp = English()
    174     nlp.add_pipe(nlp.create_pipe('sentencizer'))

[/usr/local/lib/python3.9/dist-packages/pygaggle/model/tokenize.py](https://localhost:8080/#) in SpacySenticizer()
    172 class SpacySenticizer:
    173     nlp = English()
--> 174     nlp.add_pipe(nlp.create_pipe('sentencizer'))
    175 
    176     def __init__(self, max_paragraph_length: int = None):

[/usr/local/lib/python3.9/dist-packages/spacy/language.py](https://localhost:8080/#) in create_pipe(self, name, config)
    300                 raise KeyError(Errors.E002.format(name=name))
    301         factory = self.factories[name]
--> 302         return factory(self, **config)
    303 
    304     def add_pipe(

[/usr/local/lib/python3.9/dist-packages/spacy/language.py](https://localhost:8080/#) in factory(nlp, **cfg)
   1043         def factory(nlp, **cfg):
   1044             if hasattr(obj, "from_nlp"):
-> 1045                 return obj.from_nlp(nlp, **cfg)
   1046             elif isinstance(obj, class_types):
   1047                 return obj()

pipes.pyx in spacy.pipeline.pipes.Sentencizer.from_nlp()

**TypeError: type() takes 1 or 3 arguments**

**Comment by jayralencar** [comment]
See [pygaggle/issues/327](https://github.com/castorini/pygaggle/issues/327).
